# -*- coding: utf-8 -*-
"""
Reset per-turn ephemeral fields at the start of each new turn.

This node runs immediately after ``build_initial_state`` and before any
routing / early-stop branches, ensuring no stale data from a previous
turn leaks into the current turn.

Cleared fields (decision-level, regenerated by downstream nodes each turn):
  subject, operation, clarify, policy, plan_ir, artifacts,
  chat_responded, and all confirmation-gate ephemeral fields.

Trace handling:
  Trace spans (``events``, ``timings``, ``failures``) are additive and
  preserved across turns.  However, runtime sub-keys set by individual
  nodes (``operation_decision``, ``planner_runtime``, ``synthesize_runtime``,
  ``executor``, ``rag``) are per-turn and must be cleared to prevent
  stale data on early-stop turns (e.g. greeting → chat_respond).

Preserved fields (set by build_initial_state or runner input):
  thread_id, messages, query, ui_context, memory_context,
  schema_version, output_mode, strict_selection, confirmation_mode.
"""
from __future__ import annotations

from backend.graph.state import GraphState
from backend.graph.trace import MAX_TRACE_SPANS

# Runtime sub-keys written by individual nodes each turn.
# These are cleared so that an early-stop turn does not carry
# stale runtime diagnostics from a previous full-pipeline turn.
_TRACE_RUNTIME_SUBKEYS = frozenset({
    "operation_decision",
    "planner_runtime",
    "synthesize_runtime",
    "executor",
    "rag",
})


def reset_turn_state(state: GraphState) -> dict:
    """Return a partial-state dict that nullifies all per-turn fields."""
    # Clean trace: preserve spans (events/timings/failures) but clear
    # per-turn runtime sub-keys.
    existing_trace = state.get("trace") or {}
    cleaned_trace = {
        k: v for k, v in existing_trace.items()
        if k not in _TRACE_RUNTIME_SUBKEYS
    }

    # Cap accumulated spans to prevent unbounded growth across turns.
    spans = cleaned_trace.get("spans")
    if isinstance(spans, list) and len(spans) > MAX_TRACE_SPANS:
        cleaned_trace["spans"] = spans[-MAX_TRACE_SPANS:]

    return {
        # --- Turn-level decision fields ---
        "subject": None,
        "operation": None,
        "alert_params": None,
        "alert_valid": None,
        "clarify": None,
        "policy": None,
        "plan_ir": None,
        "artifacts": None,
        "chat_responded": None,
        # --- Confirmation-gate ephemeral fields ---
        "require_confirmation": None,
        "confirmation_options": None,
        "user_confirmation": None,
        "confirmation_intent": None,
        "confirmation_instruction": None,
        # --- Trace runtime sub-keys (per-turn) ---
        "trace": cleaned_trace,
    }
