/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_models_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Model */
        post: operations["test_model_api_models_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/track-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Record */
        get: operations["track_record_api_predictions_track_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness Check
         * @description Process liveness probe; never touches external dependencies.
         */
        get: operations["liveness_check_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Dependency readiness probe used by orchestrators and Docker.
         */
        get: operations["readiness_check_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics Endpoint */
        get: operations["metrics_endpoint_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Profile */
        get: operations["get_user_profile_api_user_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watchlist */
        get: operations["get_watchlist_api_watchlist_get"];
        put?: never;
        /** Add Watchlist Item */
        post: operations["add_watchlist_item_api_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Watchlist Item */
        delete: operations["remove_watchlist_item_api_watchlist__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_conversations__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_conversations__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/price/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Price */
        get: operations["get_price_api_stock_price__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/news/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News */
        get: operations["get_news_api_stock_news__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/financials/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Financials */
        get: operations["get_financials_api_financials__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/kline/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kline Data */
        get: operations["get_kline_data_api_stock_kline__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Endpoint */
        post: operations["execute_endpoint_api_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execute/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay Events */
        get: operations["replay_events_api_execute_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/execute/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_execute_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Prediction */
        post: operations["generate_prediction_api_predictions_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/outcomes/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute Outcomes */
        post: operations["recompute_outcomes_api_predictions_outcomes_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction Run */
        get: operations["get_prediction_run_api_predictions_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest Prediction */
        get: operations["get_latest_prediction_api_predictions_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction History */
        get: operations["get_prediction_history_api_predictions_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction Stats */
        get: operations["get_prediction_stats_api_predictions_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/{prediction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction */
        get: operations["get_prediction_api_predictions__prediction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire Monitor Lease */
        post: operations["acquire_monitor_lease_api_monitor_leases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/leases/{lease_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Renew Monitor Lease */
        put: operations["renew_monitor_lease_api_monitor_leases__lease_id__put"];
        post?: never;
        /** Release Monitor Lease */
        delete: operations["release_monitor_lease_api_monitor_leases__lease_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Monitor Comments */
        get: operations["list_monitor_comments_api_monitor_comments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monitor/comments/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Monitor Comments */
        get: operations["stream_monitor_comments_api_monitor_comments_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Report Index */
        get: operations["list_report_index_api_reports_index_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/replay/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report Replay */
        get: operations["get_report_replay_api_reports_replay__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Report Share */
        post: operations["create_report_share_api_reports__report_id__share_post"];
        /** Revoke Report Share */
        delete: operations["revoke_report_share_api_reports__report_id__share_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/shared/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shared Report */
        get: operations["get_shared_report_api_reports_shared__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcquireLeaseRequest */
        AcquireLeaseRequest: {
            /** Session Id */
            session_id: string;
            /** Symbol */
            symbol: string;
        };
        /**
         * ActiveAsset
         * @description 当前激活资产
         *
         *     用于标识用户当前查看的资产，包含代码、类型和显示名称。
         */
        ActiveAsset: {
            /**
             * Symbol
             * @description 标准化代码
             */
            symbol: string;
            /**
             * Type
             * @description 资产类型
             * @enum {string}
             */
            type: "equity" | "index" | "etf" | "crypto";
            /**
             * Display Name
             * @description 显示名称
             */
            display_name: string;
        };
        /** AddWatchlistRequest */
        AddWatchlistRequest: {
            /** Ticker */
            ticker: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * AnalystTargets
         * @description 分析师目标价
         */
        AnalystTargets: {
            /** Low */
            low?: number | null;
            /** Current */
            current?: number | null;
            /** Mean */
            mean?: number | null;
            /** Median */
            median?: number | null;
            /** High */
            high?: number | null;
        };
        /**
         * Capabilities
         * @description 仪表盘能力集 - 决定前端渲染哪些组件
         *
         *     根据资产类型，不同组件会被启用或禁用。
         *     例如：equity 显示 revenue_trend，index 显示 sector_weights。
         */
        Capabilities: {
            /**
             * Revenue Trend
             * @description 营收趋势图
             * @default false
             */
            revenue_trend: boolean;
            /**
             * Segment Mix
             * @description 分部收入饼图
             * @default false
             */
            segment_mix: boolean;
            /**
             * Sector Weights
             * @description 行业权重饼图
             * @default false
             */
            sector_weights: boolean;
            /**
             * Top Constituents
             * @description 成分股排行
             * @default false
             */
            top_constituents: boolean;
            /**
             * Holdings
             * @description 持仓明细
             * @default false
             */
            holdings: boolean;
            /**
             * Market Chart
             * @description K线/折线图
             * @default true
             */
            market_chart: boolean;
        };
        /** ChatContext */
        ChatContext: {
            /** Active Symbol */
            active_symbol?: string | null;
            /** View */
            view?: string | null;
            /** Source View */
            source_view?: ("dashboard" | "command_palette") | null;
            /** Source Tab */
            source_tab?: string | null;
            selection?: components["schemas"]["SelectionContext"] | null;
            /** Selections */
            selections?: components["schemas"]["SelectionContext"][] | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @description message role
             */
            role: string;
            /**
             * Content
             * @description message content
             */
            content: string;
        };
        /** ChatOptions */
        ChatOptions: {
            /** Output Mode */
            output_mode?: ("chat" | "brief" | "investment_report") | null;
            /** Strict Selection */
            strict_selection?: boolean | null;
            /** Locale */
            locale?: string | null;
            /** Trace Raw Override */
            trace_raw_override?: ("on" | "off" | "inherit") | null;
        };
        /**
         * DashboardData
         * @description Dashboard 聚合数据 (v2)
         *
         *     v1 字段: snapshot, charts, news
         *     v2 新增: valuation, financials, technicals, peers (可空 + fallback_reason)
         */
        DashboardData: {
            /** Snapshot */
            snapshot?: {
                [key: string]: unknown;
            };
            /** Charts */
            charts?: {
                [key: string]: unknown;
            };
            /** News */
            news?: {
                [key: string]: unknown;
            };
            /** Meta */
            meta?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            valuation?: components["schemas"]["ValuationData"] | null;
            /** Valuation Fallback Reason */
            valuation_fallback_reason?: string | null;
            financials?: components["schemas"]["FinancialStatement"] | null;
            /** Financials Fallback Reason */
            financials_fallback_reason?: string | null;
            technicals?: components["schemas"]["TechnicalData"] | null;
            /** Technicals Fallback Reason */
            technicals_fallback_reason?: string | null;
            peers?: components["schemas"]["PeerComparisonData"] | null;
            /** Peers Fallback Reason */
            peers_fallback_reason?: string | null;
            macro_snapshot?: components["schemas"]["MacroSnapshotData"] | null;
            /** Macro Snapshot Fallback Reason */
            macro_snapshot_fallback_reason?: string | null;
            /** Earnings History */
            earnings_history?: components["schemas"]["EarningsHistoryEntry"][] | null;
            analyst_targets?: components["schemas"]["AnalystTargets"] | null;
            recommendations?: components["schemas"]["RecommendationsSummary"] | null;
            indicator_series?: components["schemas"]["IndicatorSeries"] | null;
        };
        /**
         * DashboardResponse
         * @description Dashboard API 响应
         *
         *     成功响应的标准格式。
         */
        DashboardResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            state: components["schemas"]["DashboardState"];
            data: components["schemas"]["DashboardData"];
        };
        /**
         * DashboardState
         * @description Dashboard 完整状态
         *
         *     包含所有影响 Dashboard 渲染的状态信息。
         */
        DashboardState: {
            active_asset: components["schemas"]["ActiveAsset"];
            capabilities: components["schemas"]["Capabilities"];
            /** Watchlist */
            watchlist: components["schemas"]["WatchItem"][];
            layout_prefs: components["schemas"]["LayoutPrefs"];
            news_mode: components["schemas"]["NewsModeConfig"];
            /** Debug */
            debug?: {
                [key: string]: unknown;
            };
        };
        /**
         * EarningsHistoryEntry
         * @description 单季度 EPS 历史记录
         */
        EarningsHistoryEntry: {
            /**
             * Quarter
             * @description e.g. '2024Q4'
             * @default
             */
            quarter: string;
            /** Eps Estimate */
            eps_estimate?: number | null;
            /** Eps Actual */
            eps_actual?: number | null;
            /** Surprise Pct */
            surprise_pct?: number | null;
        };
        /**
         * ExecuteRequest
         * @description Chat、Dashboard handoff 与报告生成共用的执行请求。
         */
        ExecuteRequest: {
            /**
             * Query
             * @description Analysis query
             */
            query: string;
            /**
             * Session Id
             * @description Conversation session ID
             */
            session_id?: string | null;
            /**
             * Run Id
             * @description Optional correlation ID
             */
            run_id?: string | null;
            /**
             * History
             * @description Visible conversation history
             */
            history?: components["schemas"]["ChatMessage"][] | null;
            /** @description Ephemeral UI context */
            context?: components["schemas"]["ChatContext"] | null;
            /** @description Chat execution options */
            options?: components["schemas"]["ChatOptions"] | null;
            /** Tickers */
            tickers?: string[] | null;
            /** Output Mode */
            output_mode?: string | null;
            /** Analysis Depth */
            analysis_depth?: ("quick" | "report" | "deep_research") | null;
            /** Budget */
            budget?: number | null;
            /** Source */
            source?: string | null;
            /** Trace Raw */
            trace_raw?: boolean | null;
        };
        /**
         * FinancialStatement
         * @description 财务报表结构化 (v2 新增)
         */
        FinancialStatement: {
            /**
             * Periods
             * @description e.g. ['2024Q4','2024Q3',...]
             */
            periods?: string[];
            /** Revenue */
            revenue?: (number | null)[];
            /** Gross Profit */
            gross_profit?: (number | null)[];
            /** Operating Income */
            operating_income?: (number | null)[];
            /** Net Income */
            net_income?: (number | null)[];
            /** Eps */
            eps?: (number | null)[];
            /** Total Assets */
            total_assets?: (number | null)[];
            /** Total Liabilities */
            total_liabilities?: (number | null)[];
            /** Operating Cash Flow */
            operating_cash_flow?: (number | null)[];
            /** Free Cash Flow */
            free_cash_flow?: (number | null)[];
        };
        /** GeneratePredictionRequest */
        GeneratePredictionRequest: {
            /** Symbol */
            symbol: string;
            /**
             * Timeframe
             * @default 1d
             * @constant
             */
            timeframe: "1d";
        };
        /** GeneratePredictionResponse */
        GeneratePredictionResponse: {
            run: components["schemas"]["PredictionRunView"];
            /** Created */
            created: boolean;
            /** Idempotent Reuse */
            idempotent_reuse: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndicatorSeries
         * @description 最近 120 日技术指标时间序列 (Phase G2)
         */
        IndicatorSeries: {
            /**
             * Dates
             * @description ISO date strings
             */
            dates?: string[];
            /** Rsi */
            rsi?: (number | null)[];
            /** Macd */
            macd?: (number | null)[];
            /** Macd Signal */
            macd_signal?: (number | null)[];
            /** Macd Histogram */
            macd_histogram?: (number | null)[];
            /** Bb Upper */
            bb_upper?: (number | null)[];
            /** Bb Middle */
            bb_middle?: (number | null)[];
            /** Bb Lower */
            bb_lower?: (number | null)[];
        };
        /** KlineResponse */
        KlineResponse: {
            /** Ticker */
            ticker: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /**
         * LayoutPrefs
         * @description 布局偏好
         *
         *     用于保存用户的组件显示偏好，支持隐藏和排序。
         */
        LayoutPrefs: {
            /**
             * Hidden Widgets
             * @description 隐藏的组件 ID
             */
            hidden_widgets?: string[];
            /**
             * Order
             * @description 组件排序
             */
            order?: string[];
        };
        /** LeaseTokenRequest */
        LeaseTokenRequest: {
            /** Lease Token */
            lease_token: string;
        };
        /**
         * MacroSnapshotData
         * @description Macro snapshot for dashboard first paint (P1).
         */
        MacroSnapshotData: {
            /** Fear Greed Index */
            fear_greed_index?: number | null;
            /**
             * Fear Greed Label
             * @default
             */
            fear_greed_label: string;
            /**
             * Sentiment Text
             * @default
             */
            sentiment_text: string;
            /** Fed Rate */
            fed_rate?: number | null;
            /** Cpi */
            cpi?: number | null;
            /** Unemployment */
            unemployment?: number | null;
            /** Gdp Growth */
            gdp_growth?: number | null;
            /** Treasury 10Y */
            treasury_10y?: number | null;
            /** Yield Spread */
            yield_spread?: number | null;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * As Of
             * @default
             */
            as_of: string;
            /**
             * Status
             * @default unavailable
             */
            status: string;
        };
        /**
         * NewsModeConfig
         * @description 新闻模式配置
         *
         *     - market: 全市场新闻 7x24
         *     - impact: 与当前资产相关的影响新闻
         */
        NewsModeConfig: {
            /**
             * Mode
             * @description 新闻模式
             * @default market
             * @enum {string}
             */
            mode: "market" | "impact";
        };
        /**
         * PeerComparisonData
         * @description 同行对比 (v2 新增)
         */
        PeerComparisonData: {
            /** Subject Symbol */
            subject_symbol: string;
            /** Peers */
            peers?: components["schemas"]["PeerMetrics"][];
        };
        /**
         * PeerMetrics
         * @description 同行单项指标
         */
        PeerMetrics: {
            /** Symbol */
            symbol: string;
            /**
             * Name
             * @default
             */
            name: string;
            /** Trailing Pe */
            trailing_pe?: number | null;
            /** Forward Pe */
            forward_pe?: number | null;
            /** Price To Book */
            price_to_book?: number | null;
            /** Ev To Ebitda */
            ev_to_ebitda?: number | null;
            /** Net Margin */
            net_margin?: number | null;
            /** Roe */
            roe?: number | null;
            /** Revenue Growth */
            revenue_growth?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Market Cap */
            market_cap?: number | null;
            /** Score */
            score?: number | null;
        };
        /** PredictionAnchor */
        PredictionAnchor: {
            /** Timeframe */
            timeframe: string;
            /** Time */
            time: string;
            /** Price */
            price: number;
        };
        /** PredictionHistoryItem */
        PredictionHistoryItem: {
            prediction: components["schemas"]["PredictionView"];
            outcome?: components["schemas"]["PredictionOutcomeView"] | null;
        };
        /** PredictionHistoryResponse */
        PredictionHistoryResponse: {
            /** Items */
            items: components["schemas"]["PredictionHistoryItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PredictionOutcomeView */
        PredictionOutcomeView: {
            /** Prediction Id */
            prediction_id: string;
            /** Status */
            status: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Entry Time */
            entry_time?: string | null;
            /** Entry Price */
            entry_price?: number | null;
            /** Pct Since Anchor */
            pct_since_anchor?: number | null;
            /** Resolution Reason */
            resolution_reason?: string | null;
            /** Evaluated Through */
            evaluated_through?: string | null;
            /** Market Provider */
            market_provider?: string | null;
            /** Market As Of */
            market_as_of?: string | null;
            /** Algorithm Version */
            algorithm_version: string;
        };
        /** PredictionPriceRange */
        PredictionPriceRange: {
            /** Low */
            low: number;
            /** High */
            high: number;
        };
        /** PredictionResponse */
        PredictionResponse: {
            prediction: components["schemas"]["PredictionView"] | null;
            outcome?: components["schemas"]["PredictionOutcomeView"] | null;
        };
        /** PredictionRunResponse */
        PredictionRunResponse: {
            run: components["schemas"]["PredictionRunView"];
        };
        /** PredictionRunView */
        PredictionRunView: {
            /** Id */
            id: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
            /** Prompt Version */
            prompt_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "unavailable" | "failed" | "cancelled";
            /** Anchor Time */
            anchor_time?: string | null;
            /** Anchor Price */
            anchor_price?: number | null;
            /** Market Provider */
            market_provider?: string | null;
            /** Market As Of */
            market_as_of?: string | null;
            /** Llm Provider */
            llm_provider?: string | null;
            /** Llm Model */
            llm_model?: string | null;
            /** Prediction Id */
            prediction_id?: string | null;
            /** Failure Code */
            failure_code?: string | null;
            /** Failure Detail */
            failure_detail?: string | null;
            /**
             * Provider Attempts
             * @default 0
             */
            provider_attempts: number;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PredictionScenario */
        PredictionScenario: {
            /** Name */
            name: string;
            /** Probability */
            probability: number;
            /** Invalidation */
            invalidation: string;
        };
        /** PredictionStatBucket */
        PredictionStatBucket: {
            /** Predictions */
            predictions: number;
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
            /** Invalidated */
            invalidated: number;
            /** Resolved */
            resolved: number;
            /** Hit Rate */
            hit_rate: number | null;
        };
        /** PredictionStatsResponse */
        PredictionStatsResponse: {
            stats: components["schemas"]["PredictionStatsView"];
        };
        /** PredictionStatsView */
        PredictionStatsView: {
            /** Predictions */
            predictions: number;
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
            /** Invalidated */
            invalidated: number;
            /** Resolved */
            resolved: number;
            /** Hit Rate */
            hit_rate: number | null;
            /** Days */
            days: number;
            /** Symbol */
            symbol: string | null;
            /** By Source */
            by_source: {
                [key: string]: components["schemas"]["PredictionStatBucket"];
            };
            /** By Direction */
            by_direction: {
                [key: string]: components["schemas"]["PredictionStatBucket"];
            };
        };
        /** PredictionView */
        PredictionView: {
            /** Prediction Id */
            prediction_id: string;
            /** Run Id */
            run_id: string;
            /** Symbol */
            symbol: string;
            /** Agent */
            agent: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "long" | "short" | "neutral";
            /** Confidence */
            confidence: number;
            /** Thesis */
            thesis: string;
            anchor: components["schemas"]["PredictionAnchor"];
            /** Entry Type */
            entry_type?: ("market" | "limit" | "stop") | null;
            /** Entry */
            entry?: number | null;
            /** Stop */
            stop?: number | null;
            /** Target1 */
            target1?: number | null;
            /** Target2 */
            target2?: number | null;
            /** Invalidation Price */
            invalidation_price?: number | null;
            /** Range Low */
            range_low?: number | null;
            /** Range High */
            range_high?: number | null;
            range?: components["schemas"]["PredictionPriceRange"] | null;
            /** Scenarios */
            scenarios: components["schemas"]["PredictionScenario"][];
            /**
             * Status
             * @enum {string}
             */
            status: "waiting" | "open" | "triggered" | "invalidated" | "hit_target" | "hit_stop" | "held_range" | "broke_range";
            /** Prompt Version */
            prompt_version: string;
            /** Evidence Provider */
            evidence_provider?: string | null;
            /** Evidence As Of */
            evidence_as_of?: string | null;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "ai" | "manual";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RecommendationsSummary
         * @description 分析师评级汇总
         */
        RecommendationsSummary: {
            /**
             * Buy
             * @default 0
             */
            buy: number;
            /**
             * Hold
             * @default 0
             */
            hold: number;
            /**
             * Sell
             * @default 0
             */
            sell: number;
            /**
             * Strong Buy
             * @default 0
             */
            strong_buy: number;
            /**
             * Strong Sell
             * @default 0
             */
            strong_sell: number;
        };
        /** RecomputeOutcomesRequest */
        RecomputeOutcomesRequest: {
            /** Prediction Id */
            prediction_id?: string | null;
            /**
             * Limit
             * @default 500
             */
            limit: number;
        };
        /** RecomputeOutcomesResponse */
        RecomputeOutcomesResponse: {
            /** Evaluated */
            evaluated: number;
            /** Prediction Id */
            prediction_id: string | null;
        };
        /** SelectionContext */
        SelectionContext: {
            /**
             * Type
             * @enum {string}
             */
            type: "news" | "filing" | "doc" | "report" | "risk" | "insight" | "url" | "web" | "article";
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Source */
            source?: string | null;
            /** Ts */
            ts?: string | null;
            /** Snippet */
            snippet?: string | null;
        };
        /** StockDataResponse */
        StockDataResponse: {
            /** Ticker */
            ticker: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Error */
            error?: string | null;
        };
        /**
         * TechnicalData
         * @description 技术面指标 (v2 新增)
         */
        TechnicalData: {
            /** Close */
            close?: number | null;
            /** Trend */
            trend?: string | null;
            /** Momentum */
            momentum?: string | null;
            /** Ma5 */
            ma5?: number | null;
            /** Ma10 */
            ma10?: number | null;
            /** Ma20 */
            ma20?: number | null;
            /** Ma50 */
            ma50?: number | null;
            /** Ma100 */
            ma100?: number | null;
            /** Ma200 */
            ma200?: number | null;
            /** Ema12 */
            ema12?: number | null;
            /** Ema26 */
            ema26?: number | null;
            /** Rsi */
            rsi?: number | null;
            /** Rsi State */
            rsi_state?: string | null;
            /** Macd */
            macd?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Macd Hist */
            macd_hist?: number | null;
            /** Stoch K */
            stoch_k?: number | null;
            /** Stoch D */
            stoch_d?: number | null;
            /** Adx */
            adx?: number | null;
            /** Cci */
            cci?: number | null;
            /** Williams R */
            williams_r?: number | null;
            /** Bollinger Upper */
            bollinger_upper?: number | null;
            /** Bollinger Middle */
            bollinger_middle?: number | null;
            /** Bollinger Lower */
            bollinger_lower?: number | null;
            /** Support Levels */
            support_levels?: number[];
            /** Resistance Levels */
            resistance_levels?: number[];
            /** Avg Volume */
            avg_volume?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValuationData
         * @description 估值指标 (v2 新增)
         */
        ValuationData: {
            /** Market Cap */
            market_cap?: number | null;
            /** Trailing Pe */
            trailing_pe?: number | null;
            /** Forward Pe */
            forward_pe?: number | null;
            /** Price To Book */
            price_to_book?: number | null;
            /** Price To Sales */
            price_to_sales?: number | null;
            /** Ev To Ebitda */
            ev_to_ebitda?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Beta */
            beta?: number | null;
            /** Week52 High */
            week52_high?: number | null;
            /** Week52 Low */
            week52_low?: number | null;
        };
        /**
         * WatchItem
         * @description 自选列表条目
         *
         *     用于 watchlist 中的每一项，包含基本标识信息。
         */
        WatchItem: {
            /**
             * Symbol
             * @description 代码
             */
            symbol: string;
            /**
             * Type
             * @description 资产类型
             * @default equity
             */
            type: string;
            /**
             * Name
             * @description 显示名称
             * @default
             */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    capabilities_api_models_capabilities_get: {
        parameters: {
            query?: {
                model?: string;
                base_url?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_api_models_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    track_record_api_predictions_track_record_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_check_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_check_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_endpoint_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_user_profile_api_user_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_watchlist_api_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    add_watchlist_item_api_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWatchlistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_watchlist_item_api_watchlist__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_conversation_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_price_api_stock_price__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_api_stock_news__ticker__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_financials_api_financials__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kline_data_api_stock_kline__ticker__get: {
        parameters: {
            query?: {
                period?: string;
                interval?: string;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KlineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query: {
                /** @description 资产代码 */
                symbol: string;
                /** @description 资产类型覆盖（可选） */
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_endpoint_api_execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_events_api_execute_runs__run_id__events_get: {
        parameters: {
            query?: {
                after_seq?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_execute_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_prediction_api_predictions_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratePredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratePredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_outcomes_api_predictions_outcomes_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecomputeOutcomesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecomputeOutcomesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_run_api_predictions_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_prediction_api_predictions_latest_get: {
        parameters: {
            query: {
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_history_api_predictions_history_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                direction?: ("long" | "short" | "neutral") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_stats_api_predictions_stats_get: {
        parameters: {
            query?: {
                symbol?: string | null;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_api_predictions__prediction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prediction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acquire_monitor_lease_api_monitor_leases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcquireLeaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    renew_monitor_lease_api_monitor_leases__lease_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lease_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_monitor_lease_api_monitor_leases__lease_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lease_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_monitor_comments_api_monitor_comments_get: {
        parameters: {
            query: {
                session_id: string;
                symbol: string;
                day?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_monitor_comments_api_monitor_comments_stream_get: {
        parameters: {
            query: {
                session_id: string;
                symbol: string;
                last_event_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_report_index_api_reports_index_get: {
        parameters: {
            query: {
                session_id: string;
                ticker?: string | null;
                query?: string | null;
                source_type?: string | null;
                include_blocked?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_replay_api_reports_replay__report_id__get: {
        parameters: {
            query: {
                session_id: string;
                include_blocked?: boolean;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_share_api_reports__report_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_report_share_api_reports__report_id__share_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shared_report_api_reports_shared__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
